### PR TITLE
update reset profile functions to latest polychromatic apis

### PR DESCRIPTION
**Pull request by eybisi**
as title says, looks like polychromatic apis changed, "get_device_state" is no longer exists. This PR fixes undefined functions and uses Middleman to get state of device and reset profile back correctly.

### CODE REVIEW

**Comment by eybisi** [comment]
probably fixes #9

**Comment by DanManN** [comment]
Thanks for the update!

**Comment by wleoncio** [comment]
I'm afraid the problem is back, should this be reopened?

**Comment by wleoncio** [comment]
One easy way out would be to add a dependency to [polychromatic](https://polychromatic.app/) and run it on vim exit to change the colors back (e.g. `polychromatic-cli -o static -c "#0000FF"`). Would you consider a PR on that?

**Pull request merged**
